name: Docker Build

on:
  push:
    branches:
      - main

env:
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: docker-teast
  REPOSITORY: expouser

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

#      - name: Build and Push Docker image
#        uses: docker/build-push-action@v2
#        with:
#          context: .
#          push: true
#          tags: /yourapp:latest

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image
        env:
          REPOSITORY: expouser
          IMAGE_TAG: 0.0.2
        run: |
          docker build --no-cache  \
          -t $REPOSITORY/$IMAGE_NAME:$IMAGE_TAG \
          -f myapp/Dockerfile .
          docker push  $REPOSITORY/$IMAGE_NAME:$IMAGE_TAG
